"""策略层公开导出接口。

通过统一 API 门面（api.py）对外暴露所有策略的标准化入口：
  screen_*   — 单只标的决策接口，返回 StrategyDecision
  scan_*     — 全市场批量扫描接口，返回 ScanResult
  explain_*  — 信号文字解释接口，返回可读字符串

依赖层次：primitives → impl → api → registry → __init__（本文件）
"""

from stock_ana.strategies.api import (
	explain_vegas_touch,
	explain_ma_squeeze,
	explain_main_rally_pullback,
	explain_momentum,
	explain_rs_acceleration,
	explain_rs_trap_alert,
	explain_triangle_ascending,
	explain_triangle_kde_setup,
	explain_triangle_parallel_channel,
	explain_triangle_rising_wedge,
	explain_triangle_vcp_setup,
	explain_vcp_setup,
	scan_ma_squeeze,
	scan_main_rally_pullback_setups,
	scan_momentum,
	scan_rs_acceleration,
	scan_rs_trap_alert,
	scan_triangle_ascending,
	scan_triangle_kde_setups,
	scan_triangle_parallel_channel,
	scan_triangle_rising_wedge,
	scan_triangle_vcp_setups,
	scan_vegas_touches,
	scan_vcp_setups,
	screen_vegas_touch,
	screen_ma_squeeze,
	screen_main_rally_pullback,
	screen_momentum,
	screen_rs_acceleration,
	screen_rs_trap_alert,
	screen_triangle_ascending,
	screen_triangle_kde_setup,
	screen_triangle_parallel_channel,
	screen_triangle_rising_wedge,
	screen_triangle_vcp_setup,
	screen_vcp_setup,
	screen_vegas_mid_pullback,
	scan_vegas_mid_pullbacks,
	explain_vegas_mid_pullback,
)
from stock_ana.strategies.contracts import ScanHit, ScanResult, StrategyDecision

__all__ = [
	"StrategyDecision",
	"ScanHit",
	"ScanResult",
	"screen_vegas_touch",
	"scan_vegas_touches",
	"explain_vegas_touch",
	"screen_vegas_mid_pullback",
	"scan_vegas_mid_pullbacks",
	"explain_vegas_mid_pullback",
	"screen_ma_squeeze",
	"scan_ma_squeeze",
	"explain_ma_squeeze",
	"screen_momentum",
	"scan_momentum",
	"explain_momentum",
	"screen_main_rally_pullback",
	"scan_main_rally_pullback_setups",
	"explain_main_rally_pullback",
	"screen_rs_acceleration",
	"scan_rs_acceleration",
	"explain_rs_acceleration",
	"screen_rs_trap_alert",
	"scan_rs_trap_alert",
	"explain_rs_trap_alert",
	"screen_triangle_ascending",
	"scan_triangle_ascending",
	"explain_triangle_ascending",
	"screen_triangle_parallel_channel",
	"scan_triangle_parallel_channel",
	"explain_triangle_parallel_channel",
	"screen_triangle_rising_wedge",
	"scan_triangle_rising_wedge",
	"explain_triangle_rising_wedge",
	"screen_triangle_kde_setup",
	"scan_triangle_kde_setups",
	"explain_triangle_kde_setup",
	"screen_triangle_vcp_setup",
	"scan_triangle_vcp_setups",
	"explain_triangle_vcp_setup",
	"screen_vcp_setup",
	"scan_vcp_setups",
	"explain_vcp_setup",
]
